server:
    build: "./server/"
    ports:
        - "8000:8000"
    volumes:
        - ./server:/server
    command: bash -c "python manage.py makemigrations todo && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
client:
    build: "./TodoClient/"
    ports:
        - "4200:4200"
    volumes:
        - ./TodoClient/:/TodoClient/
        - /TodoClient/node_modules
    command: bash -c "ng serve --host 0.0.0.0 --disableHostCheck"
